/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.17.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace Table.Data
{

  public partial class TestThriftTable : TBase
  {

    public List<global::Table.Data.TestThrift> Data { get; set; }

    public TestThriftTable()
    {
    }

    public TestThriftTable(List<global::Table.Data.TestThrift> data) : this()
    {
      this.Data = data;
    }

    public TestThriftTable DeepCopy()
    {
      var tmp5 = new TestThriftTable();
      if((Data != null))
      {
        tmp5.Data = this.Data.DeepCopy();
      }
      return tmp5;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_data = false;
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.List)
              {
                {
                  var _list6 = await iprot.ReadListBeginAsync(cancellationToken);
                  Data = new List<global::Table.Data.TestThrift>(_list6.Count);
                  for(int _i7 = 0; _i7 < _list6.Count; ++_i7)
                  {
                    global::Table.Data.TestThrift _elem8;
                    _elem8 = new global::Table.Data.TestThrift();
                    await _elem8.ReadAsync(iprot, cancellationToken);
                    Data.Add(_elem8);
                  }
                  await iprot.ReadListEndAsync(cancellationToken);
                }
                isset_data = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
        if (!isset_data)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp9 = new TStruct("TestThriftTable");
        await oprot.WriteStructBeginAsync(tmp9, cancellationToken);
        var tmp10 = new TField();
        if((Data != null))
        {
          tmp10.Name = "data";
          tmp10.Type = TType.List;
          tmp10.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp10, cancellationToken);
          await oprot.WriteListBeginAsync(new TList(TType.Struct, Data.Count), cancellationToken);
          foreach (global::Table.Data.TestThrift _iter11 in Data)
          {
            await _iter11.WriteAsync(oprot, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      if (!(that is TestThriftTable other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return TCollections.Equals(Data, other.Data);
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if((Data != null))
        {
          hashcode = (hashcode * 397) + TCollections.GetHashCode(Data);
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp12 = new StringBuilder("TestThriftTable(");
      if((Data != null))
      {
        tmp12.Append(", Data: ");
        Data.ToString(tmp12);
      }
      tmp12.Append(')');
      return tmp12.ToString();
    }
  }

}
