// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/MessageDef.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from proto/MessageDef.proto</summary>
public static partial class MessageDefReflection {

  #region Descriptor
  /// <summary>File descriptor for proto/MessageDef.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MessageDefReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChZwcm90by9NZXNzYWdlRGVmLnByb3RvKjQKClBCX01TR19DTUQSEgoOQzJT",
          "X0hFQVJUX0JFQVQQABISCg5TMkNfSEVBUlRfQkVBVBABYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::PB_MSG_CMD), }, null, null));
  }
  #endregion

}
#region Enums
/// <summary>
/// 命令
/// </summary>
public enum PB_MSG_CMD {
  [pbr::OriginalName("C2S_HEART_BEAT")] C2SHeartBeat = 0,
  [pbr::OriginalName("S2C_HEART_BEAT")] S2CHeartBeat = 1,
}

#endregion


#endregion Designer generated code
