/*
*Autogenerated by Excel2Thrift Tool
*DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
using UnityEngine;
using System;
using System.Collections;
using Thrift.Protocol;
using System.IO;
using System.Collections.Generic;
using System.Text;
using Communication;

namespace ThriftTable
{
    public abstract class AbstractDataBase
    {
        public Thrift.Protocol.TBase m_Data;
        abstract public void ParseData( byte[] bytes );
    }
    public class TestThriftData :  AbstractDataBase
    {
        public new  TestThriftTable m_Data;
        public override void ParseData(byte[] bytes)
        {
            m_Data = new TestThriftTable();
            ThriftSerialize.DeSerialize(m_Data, bytes);
        }
    }
    public class ThriftTableHolder
    {
        public enum ETXT_NAME
        {
            _Min,
            TestThrift,
            _Max,
        }
        public static Dictionary<ETXT_NAME, AbstractDataBase> m_TableDic = new Dictionary<ETXT_NAME, AbstractDataBase>()
        {
            { ETXT_NAME.TestThrift, new TestThriftData() },
        };
        public static Thrift.Protocol.TBase GetTable(ETXT_NAME en)
        {
            switch (en)
            {
                case ETXT_NAME.TestThrift:
                  return ((TestThriftData)m_TableDic[en]).m_Data;
                default:  return null;
            }
        }
    }
}
