/* *
 * ===============================================
 * author      : Josh@win
 * e-mail      : shijun_z@163.com
 * create time : 2025年6月19 15:30
 * function    : 
 * ===============================================
 * */
// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/PbMsgCMD.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from proto/PbMsgCMD.proto</summary>
public static partial class PbMsgCMDReflection {

  #region Descriptor
  /// <summary>File descriptor for proto/PbMsgCMD.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static PbMsgCMDReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChRwcm90by9QYk1zZ0NNRC5wcm90byo0CgpQQl9NU0dfQ01EEhIKDkMyU19I",
          "RUFSVF9CRUFUEAASEgoOUzJDX0hFQVJUX0JFQVQQAWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::PB_MSG_CMD), }, null, null));
  }
  #endregion

}
#region Enums
/// <summary>
/// 命令
/// </summary>
public enum PB_MSG_CMD {
  [pbr::OriginalName("C2S_HEART_BEAT")] C2SHeartBeat = 0,
  [pbr::OriginalName("S2C_HEART_BEAT")] S2CHeartBeat = 1,
}

#endregion


#endregion Designer generated code
